CC = g++
FLAGS = -std=c++11 -w -pipe -O2 -Wextra -Wall -Werror -Wno-sign-compare -Wno-unused-result -pedantic -lm
FILES = TTrie.cpp main.cpp
PROG = da4

da4:
	$(CC) $(FLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o da4